import { randomBytes,scryptSync,timingSafeEqual } from 'node:crypto';
import { NextResponse } from 'next/server';
import { db } from '@/lib/database';
import { authCookieName,verifySessionToken,type WebRole,type WebSession } from '@/lib/web-auth';

export type WebUser={id:string;username:string;display_name:string;role:WebRole;is_active:boolean;session_version:number;last_login_at:string|null;created_at:string;updated_at:string};
export function hashPassword(password:string){const salt=randomBytes(16).toString('hex');return `scrypt$${salt}$${scryptSync(password,salt,64).toString('hex')}`}
export function verifyPassword(password:string,stored:string){try{const [algorithm,salt,hash]=stored.split('$');if(algorithm!=='scrypt'||!salt||!hash)return false;const actual=scryptSync(password,salt,64),expected=Buffer.from(hash,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected)}catch{return false}}
export async function ensureBootstrapSuperadmin(){const username=process.env.WEB_ADMIN_USERNAME?.trim(),password=process.env.WEB_ADMIN_PASSWORD,displayName=username||'Superadmin';if(!username||!password)throw new Error('WEB_ADMIN_USERNAME and WEB_ADMIN_PASSWORD are required to bootstrap the first superadmin.');const client=await db.connect();try{await client.query('begin');await client.query("select pg_advisory_xact_lock(hashtext('pti_web_user_bootstrap'))");const count=await client.query('select count(*)::int count from web_users');if(count.rows[0].count===0)await client.query(`insert into web_users(username,display_name,password_hash,role) values($1,$2,$3,'SUPERADMIN')`,[username,displayName,hashPassword(password)]);await client.query('commit')}catch(error){await client.query('rollback');throw error}finally{client.release()}}
export async function findUserByUsername(username:string){const {rows}=await db.query<WebUser&{password_hash:string}>('select * from web_users where lower(username)=lower($1) limit 1',[username]);return rows[0]}
export function cookieToken(request:Request){const cookie=request.headers.get('cookie')||'';const value=cookie.split(';').map(item=>item.trim()).find(item=>item.startsWith(`${authCookieName}=`));return value?decodeURIComponent(value.slice(authCookieName.length+1)):undefined}
export async function currentWebUser(request:Request){const session=await verifySessionToken(cookieToken(request));if(!session||typeof session==='boolean')return null;const {rows}=await db.query<WebUser>('select id,username,display_name,role,is_active,session_version,last_login_at,created_at,updated_at from web_users where id=$1',[session.userId]);const user=rows[0];if(!user||!user.is_active||user.session_version!==session.sessionVersion)return null;return {user,session}}
export async function requireWebRole(request:Request,roles:WebRole[]){const current=await currentWebUser(request);if(!current)return {response:NextResponse.json({error:'Authentication required.'},{status:401})};if(!roles.includes(current.user.role))return {response:NextResponse.json({error:'You do not have permission to perform this action.'},{status:403})};return current as {user:WebUser;session:WebSession}}
