'use client';
import { useEffect,useState } from 'react';

export function DriverDetail({id}:{id:string}){
  const [data,setData]=useState<any>(null),[error,setError]=useState('');
  useEffect(()=>{void fetch(`/api/drivers/${id}`).then(async response=>{const body=await response.json();response.ok?setData(body):setError(body.error)})},[id]);
  if(error)return <p className="text-red-300">{error}</p>;
  if(!data)return <p className="text-slate-400">Loading driver…</p>;
  const driver=data.driver,current=data.assignments.find((item:any)=>!item.ended_at);
  return <><a href="/drivers" className="text-blue-400">← Drivers</a><header className="mt-5"><p className="text-sm font-semibold text-blue-400">Driver profile</p><h1 className="text-3xl font-bold">{[driver.first_name,driver.last_name].filter(Boolean).join(' ')||`@${driver.telegram_username}`}</h1><p className="mt-2 text-slate-400">{driver.telegram_username?`@${driver.telegram_username}`:'No username'} · Telegram ID {driver.telegram_user_id||'not provided'}</p><p className="text-slate-400">Current: {current?`Unit ${current.unit_number} · ${current.company} · ${current.telegram_group_title}`:'No current assignment'}</p></header><div className="mt-6 grid gap-4 sm:grid-cols-2"><Compliance title="Last 4 weeks" value={data.compliance4}/><Compliance title="Last 8 weeks" value={data.compliance8}/></div>
    <History title="PTI history" heads={['PTI','Unit','Submitted','Status','Reviewer','Defects','Archive']} rows={data.ptis.map((pti:any)=>[pti.pti_reference,pti.unit_number,new Date(pti.created_at).toLocaleString(),pti.status,pti.reviewed_by||'—',pti.defect_count,pti.archive_url?<a key={pti.id} href={pti.archive_url} target="_blank" className="text-blue-400">Telegram ↗</a>:'—'])}/>
    <History title="Defect history" heads={['Defect','Unit','Category','Severity','Status','Created']} rows={data.defects.map((defect:any)=>[<a className="text-blue-400" href={`/defects/${defect.id}`} key={defect.id}>{defect.defect_reference}</a>,defect.unit_number,defect.category,defect.severity,defect.status,new Date(defect.created_at).toLocaleDateString()])}/>
    <History title="Assignment history" heads={['Unit','Company','Group','Start','End','Reason']} rows={data.assignments.map((assignment:any)=>[assignment.unit_number,assignment.company,assignment.telegram_group_title,assignment.started_at?new Date(assignment.started_at).toLocaleString():'Unknown',assignment.ended_at?new Date(assignment.ended_at).toLocaleString():'Current',assignment.reason||'—'])}/>
  </>;
}
function Compliance({title,value}:{title:string;value:any}){return <section className="rounded-xl border border-slate-800 bg-[#15191f] p-5"><p className="text-sm text-slate-400">{title}</p><p className="text-4xl font-black text-blue-400">{value.score===null?'—':`${value.score}%`}</p><p className="mt-2 text-sm text-slate-400">Expected {value.expected} · On time {value.onTime} · Missing {value.missing} · Resends {value.resends}</p></section>}
function History({title,heads,rows}:{title:string;heads:string[];rows:React.ReactNode[][]}){return <section className="mt-8"><h2 className="mb-3 text-xl font-bold">{title}</h2><div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f]"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-slate-400"><tr>{heads.map(head=><th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t border-slate-800">{row.map((cell,cellIndex)=><td className="p-3" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-slate-500">No history available.</p>}</div></section>}
