'use client';
import { useEffect,useMemo,useState } from 'react';
import { defectCategories,defectSeverities,severityLabels,type DefectCategory,type DefectSeverity } from '@/lib/fleet-constants';
import { canManage,useCurrentUser } from '@/lib/use-current-user';

type Status='processing'|'pending_review'|'approved'|'resend_requested'|'resubmitted'|'failed';
type ExistingDefect={id:string;defect_number:string;category:string;description:string;severity:DefectSeverity;status:string};
type Submission={id:string;pti_reference:string;unit_number:string;company:string;media_type:'photo'|'video';source_chat_title:string;archive_url:string|null;status:Status;review_note:string|null;reviewed_by:string|null;reviewed_at:string|null;created_at:string;failure_reason:string|null;defect_count:number;defects:ExistingDefect[]};
type NewDefect={category:DefectCategory;severity:DefectSeverity;description:string};
const labels:Record<Status,string>={processing:'Processing',pending_review:'Pending Review',approved:'All Good',resend_requested:'Resend Requested',resubmitted:'Resubmitted',failed:'Failed'};

export function PtiReviewPage(){
  const [items,setItems]=useState<Submission[]>([]),[filter,setFilter]=useState('all'),[company,setCompany]=useState('all'),[notice,setNotice]=useState(''),[review,setReview]=useState<Submission|null>(null);const user=useCurrentUser(),mayManage=canManage(user);
  const load=async()=>{const response=await fetch('/api/pti-submissions');const body=await response.json();if(response.ok)setItems(body.submissions);else setNotice(body.error)};
  useEffect(()=>{void load()},[]);
  const companies=useMemo(()=>[...new Set(items.map(item=>item.company))].sort(),[items]);
  const rows=items.filter(item=>(filter==='all'||item.status===filter)&&(company==='all'||item.company===company));
  const pending=items.filter(item=>item.status==='pending_review').length;
  return <><header className="mb-8 flex items-start justify-between"><div><p className="text-sm font-semibold text-blue-400">PTI · Stage 2</p><h1 className="text-3xl font-bold tracking-tight text-white">PTI media review</h1><p className="mt-2 text-slate-400">Review new submissions or open any completed PTI to see its review record.</p></div><a href="/units" className="rounded-lg border border-slate-700 bg-[#15191f] px-4 py-2 text-slate-200">Assigned Units</a></header>
    <section className="mb-6 grid grid-cols-3 gap-4">{[['Total PTIs',items.length],['Pending Review',pending],['All Good',items.filter(item=>item.status==='approved').length]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-slate-800 bg-[#15191f] p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-3xl font-bold text-white">{value}</p></div>)}</section>
    <div className="mb-4 flex flex-wrap gap-3"><select className="rounded-lg border border-slate-700 bg-[#11151a] px-3 py-2" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All Statuses</option><option value="pending_review">Pending Review</option><option value="approved">All Good</option><option value="resend_requested">Resend Requested</option><option value="resubmitted">Resubmitted</option><option value="failed">Failed</option></select><select className="rounded-lg border border-slate-700 bg-[#11151a] px-3 py-2" value={company} onChange={event=>setCompany(event.target.value)}><option value="all">All Companies</option>{companies.map(value=><option key={value}>{value}</option>)}</select></div>
    {notice&&<p className="mb-3 text-sm text-amber-300">{notice}</p>}
    <div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f] shadow-xl shadow-black/10"><table className="w-full min-w-[1320px] text-left"><thead className="bg-[#101318] text-sm text-slate-400"><tr><th className="w-[10rem] p-4">PTI ID</th><th className="w-[7rem]">Unit</th><th className="w-[10rem]">Company</th><th className="w-[6rem]">Media</th><th className="w-[13rem]">Source Group</th><th className="w-[12rem]">Submitted</th><th className="w-[11rem]">Status</th><th className="w-[20rem]">Review Notes</th><th className="w-[13rem]">Telegram Message</th><th className="w-[8rem] pr-4">Actions</th></tr></thead><tbody>{rows.map(item=>{const actionable=mayManage&&['pending_review','resend_requested','approved'].includes(item.status);const actionLabel=actionable?(item.status==='approved'?'Edit Review':'Review'):item.reviewed_at?'View Review':'View Details';return <tr key={item.id} className="border-t border-slate-800 text-slate-300 transition-colors hover:bg-[#1b2027]"><td className="p-4 font-mono text-sm font-semibold text-blue-300">{item.pti_reference}</td><td className="font-semibold text-white">{item.unit_number}</td><td>{item.company}</td><td className="capitalize">{item.media_type}</td><td className="max-w-[13rem] truncate" title={item.source_chat_title}>{item.source_chat_title}</td><td className="whitespace-nowrap text-sm text-slate-400">{new Date(item.created_at).toLocaleString()}</td><td><StatusBadge status={item.status}/></td><td className="max-w-[20rem] whitespace-normal pr-4"><p className={item.review_note?'text-sm leading-5 text-slate-300':'text-sm text-slate-600'}>{item.review_note||'No notes yet'}</p></td><td className="whitespace-nowrap">{item.archive_url?<a target="_blank" rel="noreferrer" className="inline-flex items-center rounded-md px-2 py-1 text-blue-400 transition hover:bg-blue-950/50 hover:text-blue-300" href={item.archive_url}>Open in Telegram ↗</a>:<span className="inline-block max-w-[10rem] whitespace-normal text-xs leading-5 text-amber-400">Archive must be a supergroup</span>}</td><td className="pr-4"><button className={`inline-flex min-w-[6.5rem] items-center justify-center whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold transition ${actionable?'bg-blue-600 text-white shadow-md shadow-blue-950/30 hover:bg-blue-500':'border border-slate-600 bg-slate-800 text-slate-200 hover:border-slate-500 hover:bg-slate-700'}`} onClick={()=>setReview(item)}>{actionLabel}</button></td></tr>})}</tbody></table></div>
    {review&&<ReviewDialog item={review} mayManage={mayManage} onClose={()=>setReview(null)} onSaved={()=>{setReview(null);void load()}}/>}
  </>;
}

function StatusBadge({status}:{status:Status}){const style=status==='approved'?'border-emerald-700/80 bg-emerald-950/70 text-emerald-300':status==='resend_requested'?'border-amber-700/80 bg-amber-950/70 text-amber-300':status==='failed'?'border-red-700/80 bg-red-950/70 text-red-300':status==='processing'?'border-sky-700/80 bg-sky-950/70 text-sky-300':status==='resubmitted'?'border-blue-700/80 bg-blue-950/70 text-blue-300':'border-violet-700/80 bg-violet-950/70 text-violet-200';return <span className={`inline-flex items-center gap-2 whitespace-nowrap rounded-full border px-3 py-1.5 text-xs font-semibold tracking-wide ${style}`}><span className="h-1.5 w-1.5 rounded-full bg-current" aria-hidden="true" />{labels[status]}</span>}

function ReviewDialog({item,mayManage,onClose,onSaved}:{item:Submission;mayManage:boolean;onClose:()=>void;onSaved:()=>void}){
  const editable=mayManage&&['pending_review','resend_requested','approved'].includes(item.status);
  const [note,setNote]=useState(item.review_note??''),[reviewedBy,setReviewedBy]=useState(item.reviewed_by??'Fleet Team'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[defects,setDefects]=useState<NewDefect[]>([]);
  const save=async(decision:'approved'|'resend_requested')=>{if(defects.some(defect=>!defect.description.trim()))return setError('Every defect needs a description.');setBusy(true);setError('');const response=await fetch(`/api/pti-submissions/${item.id}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision,note,reviewedBy,defects,editReviewed:item.status==='approved'})});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.error);onSaved()};
  const update=(index:number,key:keyof NewDefect,value:string)=>setDefects(all=>all.map((defect,itemIndex)=>itemIndex===index?{...defect,[key]:value}:defect));
  return <div className="fixed inset-0 z-30 overflow-y-auto bg-black/75 p-4 backdrop-blur-sm"><div className="mx-auto my-4 w-full max-w-2xl rounded-xl border border-slate-700 bg-[#171b21] p-6 shadow-2xl"><p className="font-mono text-sm font-semibold text-blue-300">{item.pti_reference}</p><h2 className="mt-1 text-xl font-bold text-white">{editable?'Review':'Review record'} · Unit {item.unit_number}</h2><div className="mt-3 flex items-center gap-3"><StatusBadge status={item.status}/><span className="text-sm text-slate-500">Submitted {new Date(item.created_at).toLocaleString()}</span></div>
    {editable?<><label className="mt-5 block text-sm text-slate-300">Fleet member<input className="mt-1 w-full rounded-lg border border-slate-700 bg-[#0f1216] px-3 py-2" value={reviewedBy} onChange={event=>setReviewedBy(event.target.value)}/></label><label className="mt-4 block text-sm text-slate-300">Review note<textarea className="mt-1 min-h-20 w-full rounded-lg border border-slate-700 bg-[#0f1216] px-3 py-2" value={note} onChange={event=>setNote(event.target.value)} placeholder="Review note or resend instructions."/></label><div className="mt-5 flex items-center justify-between"><h3 className="font-bold">Add defects ({defects.length})</h3><button className="rounded-lg border border-blue-700 px-3 py-2 text-sm text-blue-300" onClick={()=>setDefects(all=>[...all,{category:'Tire',severity:'ATTENTION',description:''}])}>+ Add Defect</button></div><div className="mt-3 space-y-3">{defects.map((defect,index)=><div key={index} className="rounded-lg border border-slate-700 bg-slate-950/50 p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-slate-400">Category<select value={defect.category} onChange={event=>update(index,'category',event.target.value)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2">{defectCategories.map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm text-slate-400">Severity<select value={defect.severity} onChange={event=>update(index,'severity',event.target.value)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2">{defectSeverities.map(value=><option key={value} value={value}>{severityLabels[value]}</option>)}</select></label></div><label className="mt-3 block text-sm text-slate-400">Description<textarea value={defect.description} onChange={event=>update(index,'description',event.target.value)} className="mt-1 min-h-20 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label><button className="mt-2 text-sm text-red-400" onClick={()=>setDefects(all=>all.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button></div>)}</div></>:<ReviewSummary item={item}/>}
    {error&&<p className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-6 flex flex-wrap justify-end gap-3"><button disabled={busy} className="rounded-lg border border-slate-700 bg-slate-800 px-4 py-2" onClick={onClose}>Close</button>{editable&&<><button disabled={busy} className="rounded-lg bg-amber-600 px-4 py-2 text-white" onClick={()=>void save('resend_requested')}>Save + Request Resend</button><button disabled={busy} className="rounded-lg bg-emerald-600 px-4 py-2 text-white" onClick={()=>void save('approved')}>Save + Approve PTI</button></>}</div></div></div>;
}

function ReviewSummary({item}:{item:Submission}){return <div className="mt-5 space-y-4"><section className="rounded-lg border border-slate-700 bg-slate-950/50 p-4"><p className="text-xs uppercase tracking-wide text-slate-500">Reviewed by</p><p className="mt-1 text-white">{item.reviewed_by||'Not reviewed yet'}</p>{item.reviewed_at&&<p className="text-sm text-slate-500">{new Date(item.reviewed_at).toLocaleString()}</p>}<p className="mt-4 text-xs uppercase tracking-wide text-slate-500">Review note</p><p className="mt-1 text-slate-200">{item.review_note||'No review note was entered.'}</p>{item.failure_reason&&<p className="mt-4 text-red-300">Failure: {item.failure_reason}</p>}</section><section><h3 className="font-bold">Defects ({item.defects.length})</h3><div className="mt-2 space-y-2">{item.defects.length?item.defects.map(defect=><a href={`/defects/${defect.id}`} key={defect.id} className="block rounded-lg border border-slate-700 bg-slate-950/50 p-3 hover:border-blue-700"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-blue-300">DEF-{String(defect.defect_number).padStart(6,'0')} · {defect.category}</b><span className={defect.severity==='CRITICAL'?'text-red-400':defect.severity==='ATTENTION'?'text-amber-300':'text-emerald-300'}>{severityLabels[defect.severity]}</span></div><p className="mt-1 text-sm text-slate-300">{defect.description}</p><p className="mt-1 text-xs text-slate-500">{defect.status.replaceAll('_',' ')}</p></a>):<p className="text-sm text-slate-500">No defects were recorded for this PTI.</p>}</div></section></div>}
