'use client';
import { useEffect,useState } from 'react';
import { startOfMondayWeek } from '@/lib/date-ranges';

export function ReportsPage(){
  const [week,setWeek]=useState(startOfMondayWeek()),[data,setData]=useState<any>(null),[error,setError]=useState('');
  useEffect(()=>{void fetch(`/api/reports/weekly?week=${week}`).then(async response=>{const body=await response.json();response.ok?setData(body):setError(body.error)})},[week]);
  return <>
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-400">Management reporting</p><h1 className="text-3xl font-bold">Weekly PTI Report</h1><p className="mt-2 text-slate-400">Printable Monday–Sunday operational summary.</p></div><div className="flex gap-3 print:hidden"><input type="date" value={week} onChange={event=>setWeek(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-2"/><a href={`/api/reports/weekly?week=${week}&format=csv`} className="rounded-lg border border-slate-700 px-4 py-2">Download CSV</a><button onClick={()=>print()} className="rounded-lg bg-blue-600 px-4 py-2">Print / PDF</button></div></header>
    {error&&<p className="text-red-300">{error}</p>}
    {data&&<><p className="mb-5 text-slate-400">Week of {data.weekStart} through {data.weekEnd}</p><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Card label="Active units" value={data.summary.active_units}/><Card label="Expected" value={data.compliance.expected}/><Card label="Submitted" value={data.compliance.submitted}/><Card label="Missing" value={data.compliance.missing}/><Card label="Fleet compliance" value={data.compliance.score===null?'—':`${data.compliance.score}%`}/><Card label="Approved" value={data.reviews.approved}/><Card label="Resend requested" value={data.reviews.resend_requested}/><Card label="Defects opened" value={data.summary.defects_opened}/><Card label="Critical" value={data.summary.critical_defects} danger/><Card label="Resolved" value={data.summary.defects_resolved}/></section>
      <Table title="Missing PTIs" heads={['Unit','Driver','Company','Last PTI','Last Notified','Group']} rows={data.missing.map((item:any)=>[item.unit_number,[item.driver_first_name,item.driver_last_name].filter(Boolean).join(' ')||item.driver_username||'Unknown',item.company,fmt(item.last_pti),fmt(item.last_notified),item.telegram_chat_title])}/>
      <Table title="Low compliance · 8 weeks" heads={['Driver','Score','Expected','Missing','Resends']} rows={data.lowCompliance.map((item:any)=>[[item.first_name,item.last_name].filter(Boolean).join(' ')||item.telegram_username||'Unknown',`${item.score}%`,item.expected,item.missing,item.resends])}/>
      <Table title="Critical defects" heads={['Defect','Unit','Driver','Category','Description','Status']} rows={data.critical.map((item:any)=>[`DEF-${String(item.defect_number).padStart(6,'0')}`,item.unit_number,item.driver_name_snapshot||item.driver_username_snapshot||'Unknown',item.category,item.description,item.status])}/>
      <Table title="Repeat problems · 8 weeks" heads={['Unit','Category','Occurrences','First','Latest']} rows={data.repeatIssues.map((item:any)=>[item.unit_number,item.category,item.occurrences,fmt(item.first_occurrence),fmt(item.latest_occurrence)])}/>
      <Table title="Reassignments" heads={['Unit','Driver','Company','Date','Reason']} rows={data.reassignments.map((item:any)=>[item.unit_number,[item.driver_first_name,item.driver_last_name].filter(Boolean).join(' ')||item.driver_username,item.company,fmt(item.created_at),item.reason||'—'])}/>
      <Table title="Defect summary" heads={['Status','Severity','Category','Count']} rows={data.defectBreakdown.map((item:any)=>[item.status,item.severity,item.category,item.count])}/>
    </>}
  </>;
}
function Card({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <div className={`rounded-xl border bg-[#15191f] p-4 ${danger&&Number(value)?'border-red-700':'border-slate-800'}`}><p className="text-xs text-slate-400">{label}</p><p className={`text-2xl font-bold ${danger&&Number(value)?'text-red-400':''}`}>{value}</p></div>}
function Table({title,heads,rows}:{title:string;heads:string[];rows:any[][]}){return <section className="mt-8 break-inside-avoid"><h2 className="mb-3 text-xl font-bold">{title}</h2><div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f]"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-slate-400"><tr>{heads.map(head=><th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t border-slate-800">{row.map((cell,cellIndex)=><td className="p-3" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-slate-500">No records for this section.</p>}</div></section>}
function fmt(value:string|null){return value?new Date(value).toLocaleString():'Never'}
