'use client';

import { useEffect, useMemo, useState } from 'react';
import { groupNeedsReassignment } from '@/lib/unit-status';
import { parseBulkUnits, type BulkUnit } from '@/lib/bulk-units';

type Registration = { is_active: boolean; telegram_chat_title: string; driver_first_name: string | null; driver_last_name: string | null; driver_username: string | null };
type Unit = { id: string; unit_number: string; company: string; registration_status: 'registered' | 'not_registered'; unit_registrations: Registration[]; pti_sent_this_week: boolean; last_pti_at: string | null; last_notified_at: string | null };

export function UnitsPage() {
  const [units, setUnits] = useState<Unit[]>([]);
  const [filter, setFilter] = useState('all');
  const [companyFilter, setCompanyFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  const [code, setCode] = useState<{ unit: string; value: string; expiresAt: string } | null>(null);
  const [showAddUnit, setShowAddUnit] = useState(false);
  const [showBulkAdd, setShowBulkAdd] = useState(false);

  const load = async () => { const res = await fetch('/api/units'); if (res.ok) setUnits((await res.json()).units); else setNotice('Unable to load units. Check DATABASE_URL and PostgreSQL.'); };
  useEffect(() => { void load(); }, []);
  const companies = useMemo(() => [...new Set(units.map(unit => unit.company))].sort(), [units]);
  const rows = useMemo(() => units.filter(unit => {
    const registration = unit.unit_registrations.find(item => item.is_active);
    const haystack = `${unit.unit_number} ${registration?.telegram_chat_title ?? ''} ${registration?.driver_first_name ?? ''} ${registration?.driver_last_name ?? ''}`.toLowerCase();
    const matches = filter === 'all' || (filter === 'registered' && unit.registration_status === 'registered') || (filter === 'not_registered' && unit.registration_status === 'not_registered') || (filter === 'sent' && unit.pti_sent_this_week) || (filter === 'missing' && unit.registration_status === 'registered' && !unit.pti_sent_this_week);
    return matches && (companyFilter === 'all' || unit.company === companyFilter) && haystack.includes(search.toLowerCase());
  }), [units, filter, companyFilter, search]);

  const registered = units.filter(unit => unit.registration_status === 'registered').length;
  const sent = units.filter(unit => unit.registration_status === 'registered' && unit.pti_sent_this_week).length;
  const missing = units.filter(unit => unit.registration_status === 'registered' && !unit.pti_sent_this_week).length;
  const eligibleMissing = units.filter(unit => { const registration = unit.unit_registrations.find(item => item.is_active); return registration && !unit.pti_sent_this_week && !groupNeedsReassignment(registration.telegram_chat_title); }).length;

  const addUnit = async (unitNumber: string, company: string) => { setBusy('add-unit'); setNotice('Adding unit…'); const res = await fetch('/api/units', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ unitNumber, company }) }); const body = await res.json(); setBusy(null); if (!res.ok) { setNotice(body.error); return false; } setNotice(`Unit ${body.unit.unit_number} added successfully.`); setShowAddUnit(false); await load(); return true; };
  const bulkAddUnits = async (items: Array<{ unitNumber: string; company: string }>) => { setBusy('bulk-add'); setNotice(`Adding ${items.length} units…`); const res = await fetch('/api/units/bulk', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ units: items }) }); const body = await res.json(); setBusy(null); if (!res.ok) { setNotice(body.error); return false; } setNotice(`Added ${body.added} unit${body.added === 1 ? '' : 's'}${body.skipped ? `; skipped ${body.skipped} duplicate${body.skipped === 1 ? '' : 's'}.` : '.'}`); setShowBulkAdd(false); await load(); return true; };
  const generate = async (unit: Unit) => { setBusy(unit.id); setNotice('Generating…'); const res = await fetch(`/api/units/${unit.id}/code`, { method: 'POST' }); const body = await res.json(); setBusy(null); if (!res.ok) return setNotice(body.error); setCode({ unit: unit.unit_number, value: body.code, expiresAt: body.expiresAt }); setNotice('Code generated successfully.'); };
  const unregister = async (unit: Unit) => { if (!confirm(`Unregister Unit ${unit.unit_number}? Registration history will remain.`)) return; setBusy(unit.id); const res = await fetch(`/api/units/${unit.id}/unregister`, { method: 'POST' }); const body = await res.json(); setBusy(null); setNotice(res.ok ? `Unit ${unit.unit_number} has been unregistered.` : body.error); if (res.ok) await load(); };
  const notifyOne = async (unit: Unit) => { setBusy(`notify-${unit.id}`); setNotice(`Notifying Unit ${unit.unit_number}…`); const res = await fetch(`/api/units/${unit.id}/notify`, { method: 'POST' }); const body = await res.json(); setBusy(null); setNotice(res.ok ? `Reminder sent to Unit ${unit.unit_number}.` : body.error); if (res.ok) await load(); };
  const notifyAll = async () => { setBusy('notify-all'); setNotice('Sending reminders to all missing units…'); const res = await fetch('/api/units/notify', { method: 'POST' }); const body = await res.json(); setBusy(null); if (!res.ok) setNotice(body.error); else setNotice(`Sent ${body.notified} reminder${body.notified === 1 ? '' : 's'}${body.failed.length ? `; ${body.failed.length} failed.` : '.'}`); await load(); };

  return <>
    <div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-400">PTI · Assigned Units</p><h1 className="text-3xl font-bold tracking-tight text-white">Weekly PTI tracking</h1><p className="mt-2 text-slate-400">See submissions and remind drivers from one place.</p></div><div className="flex flex-wrap gap-3"><a href="/pti" className="rounded-lg border border-slate-700 bg-[#15191f] px-4 py-2.5 font-semibold text-slate-200 transition hover:-translate-y-0.5 hover:border-slate-600 hover:bg-[#1d232b]">PTI Review</a><button disabled={!eligibleMissing || busy === 'notify-all'} className="rounded-lg bg-amber-500 px-4 py-2.5 font-semibold text-black shadow-lg shadow-amber-950/30 transition hover:-translate-y-0.5 hover:bg-amber-400 disabled:cursor-not-allowed disabled:opacity-40" onClick={() => void notifyAll()}>{busy === 'notify-all' ? 'Notifying…' : `Notify all missing (${eligibleMissing})`}</button><button className="rounded-lg border border-blue-700 bg-blue-950/50 px-4 py-2.5 font-semibold text-blue-200 shadow-lg shadow-blue-950/20 transition hover:-translate-y-0.5 hover:border-blue-500 hover:bg-blue-900/60" onClick={() => setShowBulkAdd(true)}>Bulk Add</button><button className="rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white shadow-lg shadow-blue-950/30 transition hover:-translate-y-0.5 hover:bg-blue-500" onClick={() => setShowAddUnit(true)}>+ Add Unit</button></div></div>
    <section className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Assigned', registered, 'text-white'], ['Sent this week', sent, 'text-emerald-400'], ['Missing PTI', missing, 'text-amber-400'], ['Not registered', units.length - registered, 'text-slate-300']].map(([label, value, color]) => <div className="rounded-xl border border-slate-800 bg-[#15191f] p-5 shadow-xl shadow-black/10 transition duration-300 hover:-translate-y-1 hover:border-slate-700 hover:bg-[#191e25]" key={String(label)}><p className="text-sm text-slate-400">{label}</p><p className={`mt-1 text-3xl font-bold ${color}`}>{value}</p></div>)}</section>
    <div className="mb-4 flex flex-wrap gap-3"><input className="rounded-lg border border-slate-700 bg-[#11151a] px-3 py-2 text-slate-100 placeholder:text-slate-500" placeholder="Search unit, driver, or group" value={search} onChange={event => setSearch(event.target.value)} /><select aria-label="Filter by company" className="rounded-lg border border-slate-700 bg-[#11151a] px-3 py-2 text-slate-200" value={companyFilter} onChange={event => setCompanyFilter(event.target.value)}><option value="all">All Companies</option>{companies.map(company => <option key={company} value={company}>{company}</option>)}</select>{[['all', 'All'], ['missing', 'Missing PTI'], ['sent', 'Sent'], ['registered', 'Registered'], ['not_registered', 'Not Registered']].map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg border px-3 py-2 text-sm transition ${filter === value ? 'border-blue-500 bg-blue-600 text-white shadow-lg shadow-blue-950/30' : 'border-slate-700 bg-[#15191f] text-slate-300 hover:border-slate-600 hover:bg-[#1d232b] hover:text-white'}`}>{label}</button>)}</div>
    {notice && <p className="mb-3 text-sm text-slate-300" role="status">{notice}</p>}
    <div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f] shadow-xl shadow-black/20"><table className="w-full min-w-[1120px] text-left"><thead className="bg-[#101318] text-sm text-slate-400"><tr><th className="p-4">Unit</th><th>Company</th><th>Driver</th><th>Telegram Group</th><th>This Week</th><th>Last PTI</th><th>Last Notified</th><th className="pr-4">Actions</th></tr></thead><tbody>{rows.map(unit => {
      const registration = unit.unit_registrations.find(item => item.is_active); const driver = registration ? [registration.driver_first_name, registration.driver_last_name].filter(Boolean).join(' ') || (registration.driver_username ? `@${registration.driver_username.replace(/^@/, '')}` : '—') : '—'; const needsReassignment = groupNeedsReassignment(registration?.telegram_chat_title);
      return <tr className={`border-t transition-colors duration-200 ${needsReassignment ? 'border-red-900/70 bg-red-950/35 text-red-100 hover:bg-red-950/55' : 'border-slate-800 text-slate-300 hover:bg-[#1b2027]'}`} key={unit.id}><td className="p-4 font-semibold"><a className={needsReassignment ? 'text-red-300 hover:text-red-200 hover:underline' : 'text-blue-400 hover:text-blue-300 hover:underline'} href={`/units/${unit.id}`}>{unit.unit_number}</a></td><td>{unit.company}</td><td>{driver}</td><td>{registration?.telegram_chat_title ?? '—'}{needsReassignment && <span className="ml-2 rounded-full border border-red-700 bg-red-950 px-2 py-0.5 text-xs font-semibold text-red-300">Reassign</span>}</td><td>{!registration ? <Badge tone="gray">Not assigned</Badge> : unit.pti_sent_this_week ? <Badge tone="green">Sent</Badge> : <Badge tone="amber">Missing</Badge>}</td><td>{formatDate(unit.last_pti_at)}</td><td>{formatDate(unit.last_notified_at)}</td><td className="pr-4"><div className="flex items-center gap-1">{registration ? <><button disabled={needsReassignment || busy === `notify-${unit.id}`} title={needsReassignment ? 'Reassign this inactive group first' : 'Send a reminder now'} className="rounded-md px-2 py-1 text-amber-300 transition hover:bg-amber-950/50 hover:text-amber-200 disabled:cursor-not-allowed disabled:opacity-35" onClick={() => void notifyOne(unit)}>{busy === `notify-${unit.id}` ? 'Sending…' : 'Notify'}</button><button disabled={busy === unit.id} className="rounded-md px-2 py-1 text-red-400 transition hover:bg-red-950/50 hover:text-red-300" onClick={() => void unregister(unit)}>Unregister</button></> : <button disabled={busy === unit.id} className="rounded-md px-2 py-1 text-blue-400 transition hover:bg-blue-950/50 hover:text-blue-300" onClick={() => void generate(unit)}>{busy === unit.id ? 'Generating…' : 'Generate Code'}</button>}</div></td></tr>;
    })}</tbody></table></div>
    {showAddUnit && <AddUnitDialog busy={busy === 'add-unit'} companies={companies} onAdd={addUnit} onClose={() => setShowAddUnit(false)} />}{showBulkAdd && <BulkAddDialog busy={busy === 'bulk-add'} onAdd={bulkAddUnits} onClose={() => setShowBulkAdd(false)} />}{code && <CodeDialog item={code} onClose={() => setCode(null)} />}
  </>;
}

function Badge({ tone, children }: { tone: 'gray' | 'green' | 'amber'; children: React.ReactNode }) { const colors = { gray: 'border-slate-700 bg-slate-800 text-slate-300', green: 'border-emerald-800 bg-emerald-950/60 text-emerald-300', amber: 'border-amber-800 bg-amber-950/60 text-amber-300' }; return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${colors[tone]}`}>{children}</span>; }
function formatDate(value: string | null) { if (!value) return 'Never'; return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)); }
function AddUnitDialog({ busy, companies, onAdd, onClose }: { busy: boolean; companies: string[]; onAdd: (unitNumber: string, company: string) => Promise<boolean>; onClose: () => void }) { const [unitNumber, setUnitNumber] = useState(''); const [company, setCompany] = useState(''); return <div className="fixed inset-0 z-10 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><form className="w-full max-w-md rounded-xl border border-slate-700 bg-[#171b21] p-6 shadow-2xl shadow-black/50" onSubmit={event => { event.preventDefault(); void onAdd(unitNumber, company); }}><h2 className="text-xl font-bold text-white">Add Unit</h2><label className="mt-5 block text-sm font-medium text-slate-300">Unit number<input autoFocus required maxLength={40} pattern="[A-Za-z0-9-]+" className="mt-1 w-full rounded-lg border border-slate-700 bg-[#0f1216] px-3 py-2 text-white placeholder:text-slate-600" value={unitNumber} onChange={event => setUnitNumber(event.target.value)} placeholder="6306" /></label><label className="mt-4 block text-sm font-medium text-slate-300">Company<input required maxLength={120} list="company-options" className="mt-1 w-full rounded-lg border border-slate-700 bg-[#0f1216] px-3 py-2 text-white placeholder:text-slate-600" value={company} onChange={event => setCompany(event.target.value)} placeholder="PTI" /></label><datalist id="company-options">{companies.map(value => <option key={value} value={value} />)}</datalist><div className="mt-6 flex justify-end gap-3"><button type="button" className="rounded-lg border border-slate-700 bg-slate-800 px-4 py-2 text-slate-200 hover:border-slate-600 hover:bg-slate-700" onClick={onClose} disabled={busy}>Cancel</button><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 text-white shadow-lg shadow-blue-950/30 hover:bg-blue-500" disabled={busy}>{busy ? 'Adding…' : 'Add Unit'}</button></div></form></div>; }
function BulkAddDialog({ busy, onAdd, onClose }: { busy: boolean; onAdd: (units: BulkUnit[]) => Promise<boolean>; onClose: () => void }) { const [value, setValue] = useState(''); const parsed = useMemo(() => parseBulkUnits(value), [value]); return <div className="fixed inset-0 z-10 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><form className="w-full max-w-2xl rounded-xl border border-slate-700 bg-[#171b21] p-6 shadow-2xl shadow-black/50" onSubmit={event => { event.preventDefault(); if (parsed.units.length && !parsed.errors.length) void onAdd(parsed.units); }}><h2 className="text-xl font-bold text-white">Bulk Add Units</h2><p className="mt-2 text-sm text-slate-400">Enter one unit per line as <span className="font-mono text-slate-200">unit number, company</span>. You can also paste two columns directly from Excel or Google Sheets.</p><textarea autoFocus rows={12} className="mt-5 w-full resize-y rounded-lg border border-slate-700 bg-[#0f1216] px-3 py-3 font-mono text-sm text-white outline-none placeholder:text-slate-600 focus:border-blue-500" value={value} onChange={event => setValue(event.target.value)} placeholder={'6306, PTI\n6307, PTI\nA-120\tFleet Company'} /><div className="mt-3 flex items-start justify-between gap-4 text-sm"><p className={parsed.units.length ? 'text-emerald-400' : 'text-slate-500'}>{parsed.units.length} valid unit{parsed.units.length === 1 ? '' : 's'}</p>{parsed.errors.length > 0 && <div className="max-w-md text-right text-red-400"><p className="font-semibold">Fix {parsed.errors.length} error{parsed.errors.length === 1 ? '' : 's'}:</p>{parsed.errors.slice(0, 4).map(error => <p key={error}>{error}</p>)}{parsed.errors.length > 4 && <p>…and {parsed.errors.length - 4} more</p>}</div>}</div><p className="mt-3 text-xs text-slate-500">Units already in the system will be skipped safely.</p><div className="mt-6 flex justify-end gap-3"><button type="button" className="rounded-lg border border-slate-700 bg-slate-800 px-4 py-2 text-slate-200 hover:border-slate-600 hover:bg-slate-700" onClick={onClose} disabled={busy}>Cancel</button><button type="submit" className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white shadow-lg shadow-blue-950/30 hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-40" disabled={busy || !parsed.units.length || parsed.errors.length > 0}>{busy ? 'Adding units…' : `Add ${parsed.units.length || ''} Unit${parsed.units.length === 1 ? '' : 's'}`}</button></div></form></div>; }
function CodeDialog({ item, onClose }: { item: { unit: string; value: string; expiresAt: string }; onClose: () => void }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []); const left = Math.max(0, new Date(item.expiresAt).getTime() - now); const command = `/activate ${item.value} @driverusername`; return <div className="fixed inset-0 z-10 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-xl border border-slate-700 bg-[#171b21] p-6 shadow-2xl shadow-black/50"><h2 className="text-xl font-bold text-white">Unit {item.unit}</h2><p className="mt-4 text-sm text-slate-400">Authorization Code</p><p className="font-mono text-4xl font-bold tracking-widest text-white">{left ? item.value : 'Expired'}</p><p className="mt-2 text-sm text-slate-300">{left ? `Expires in: ${String(Math.floor(left / 60000)).padStart(2, '0')}:${String(Math.floor(left / 1000) % 60).padStart(2, '0')}` : 'Generate a new code to activate this unit.'}</p><p className="mt-4 rounded-lg border border-slate-700 bg-[#0f1216] p-3 font-mono text-sm text-slate-200">{command}</p><div className="mt-5 flex justify-end gap-3"><button className="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-slate-200 hover:bg-slate-700" onClick={onClose}>Close</button><button className="rounded-lg bg-blue-600 px-3 py-2 text-white shadow-lg shadow-blue-950/30 hover:bg-blue-500" onClick={() => navigator.clipboard.writeText(command)}>Copy Command</button></div></div></div>; }
