'use client';
import { useEffect,useState } from 'react';
import { useCurrentUser } from '@/lib/use-current-user';

type Role='VIEWER'|'ADMIN'|'SUPERADMIN'|'USERADMIN';
type Access={companyName:string;canView:boolean;canEdit:boolean};
type User={id:string;username:string;display_name:string;role:Role;is_active:boolean;last_login_at:string|null;created_at:string;company_access:Access[]};
type Company={name:string;is_active:boolean};

export function UserManagementPage(){
  const manager=useCurrentUser(),[users,setUsers]=useState<User[]>([]),[companies,setCompanies]=useState<Company[]>([]),[show,setShow]=useState<User|null|true|false>(false),[notice,setNotice]=useState('');
  const load=async()=>{const [usersResponse,companyResponse]=await Promise.all([fetch('/api/admin/users'),fetch('/api/companies')]);const userBody=await usersResponse.json();const companyBody=await companyResponse.json();usersResponse.ok?setUsers(userBody.users):setNotice(userBody.error);if(companyResponse.ok)setCompanies(companyBody.companies.filter((item:Company)=>item.is_active));};
  useEffect(()=>{void load()},[]);
  return <><header className="mb-8 flex items-start justify-between"><div><p className="text-sm font-semibold text-blue-400">{manager?.role==='USERADMIN'?'UserAdmin':'Superadmin'}</p><h1 className="text-3xl font-bold">User Management</h1><p className="mt-2 text-slate-400">Assign company-level view and edit access for each account. UserAdmins can manage Viewer and Admin accounts; only Superadmins control companies and elevated roles.</p></div><button onClick={()=>setShow(true)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold">+ Add User</button></header>{notice&&<p className="mb-4 text-amber-300">{notice}</p>}<div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f]"><table className="w-full min-w-[850px] text-left"><thead className="text-sm text-slate-400"><tr><th className="p-4">User</th><th>Role</th><th>Status</th><th>Last Login</th><th>Created</th><th>Action</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-slate-800"><td className="p-4"><b>{user.display_name}</b><p className="text-sm text-slate-500">{user.username}</p></td><td><RoleBadge role={user.role}/></td><td className={user.is_active?'text-emerald-300':'text-red-300'}>{user.is_active?'Active':'Disabled'}</td><td>{user.last_login_at?new Date(user.last_login_at).toLocaleString():'Never'}</td><td>{new Date(user.created_at).toLocaleDateString()}</td><td><button onClick={()=>setShow(user)} className="rounded border border-slate-600 px-3 py-1 text-sm">{manager?.role==='USERADMIN'?'Company access':'Manage'}</button></td></tr>)}</tbody></table></div>{show&&<UserDialog existing={typeof show==='object'?show:null} companies={companies} managerRole={manager?.role||'SUPERADMIN'} onClose={()=>setShow(false)} onSaved={()=>{setShow(false);void load()}}/>}</>;
}
function RoleBadge({role}:{role:Role}){const colors=role==='SUPERADMIN'?'border-purple-700 text-purple-300':role==='USERADMIN'?'border-amber-700 text-amber-300':role==='ADMIN'?'border-blue-700 text-blue-300':'border-slate-600 text-slate-300';return <span className={`rounded-full border px-2 py-1 text-xs font-semibold ${colors}`}>{role}</span>}
function UserDialog({existing,companies,managerRole,onClose,onSaved}:{existing:User|null;companies:Company[];managerRole:Role;onClose:()=>void;onSaved:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[role,setRole]=useState<Role>(existing?.role||'VIEWER');
  const [access,setAccess]=useState<Access[]>(()=>companies.map(company=>existing?.company_access?.find(item=>item.companyName===company.name)||{companyName:company.name,canView:false,canEdit:false}));
  useEffect(()=>{setAccess(companies.map(company=>existing?.company_access?.find(item=>item.companyName===company.name)||{companyName:company.name,canView:false,canEdit:false}))},[companies,existing]);
  const userAdmin=managerRole==='USERADMIN';const canEditProfile=!userAdmin||!existing;
  const toggle=(companyName:string,mode:'canView'|'canEdit',enabled:boolean)=>setAccess(current=>current.map(item=>item.companyName===companyName?{...item,[mode]:enabled,...(mode==='canView'&&!enabled?{canEdit:false}:{}),...(mode==='canEdit'&&enabled?{canView:true}:{})}:item));
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError('');try{
    const form=new FormData(event.currentTarget);let response:Response;
    if(existing){
      if(!userAdmin){const payload={displayName:form.get('displayName'),role,isActive:form.get('isActive')==='on',password:form.get('password')};response=await fetch(`/api/admin/users/${existing.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error)}
      if(existing.role!=='SUPERADMIN'&&existing.role!=='USERADMIN'){response=await fetch(`/api/admin/users/${existing.id}/company-access`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({companyAccess:access})});const body=await response.json();if(!response.ok)throw new Error(body.error)}
    }else{
      const payload={username:form.get('username'),displayName:form.get('displayName'),password:form.get('password'),role,companyAccess:access};response=await fetch('/api/admin/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error);
    }
    onSaved();
  }catch(cause){setError(cause instanceof Error?cause.message:'Unable to save user.')}finally{setBusy(false)}};
  return <div className="fixed inset-0 z-30 overflow-y-auto bg-black/75 p-4"><form onSubmit={submit} className="mx-auto my-6 w-full max-w-2xl rounded-xl border border-slate-700 bg-[#171b21] p-6"><h2 className="text-xl font-bold">{existing?(userAdmin?'Configure Company Access':'Manage User'):'Add User'}</h2>{canEditProfile&&<><label className="mt-4 block text-sm text-slate-400">Username<input name="username" required={!existing} disabled={Boolean(existing)} defaultValue={existing?.username||''} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2 disabled:opacity-60"/></label><label className="mt-3 block text-sm text-slate-400">Display name<input name="displayName" required defaultValue={existing?.display_name||''} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label><label className="mt-3 block text-sm text-slate-400">Role<select name="role" value={role} onChange={event=>{const next=event.target.value as Role;setRole(next);if(next==='VIEWER')setAccess(current=>current.map(item=>({...item,canEdit:false})))}} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2">{managerRole==='SUPERADMIN'?<><option value="VIEWER">Viewer — read only</option><option value="ADMIN">Admin — scoped fleet operations</option><option value="USERADMIN">UserAdmin — configure users and company access</option><option value="SUPERADMIN">Superadmin — company and system management</option></>:<><option value="VIEWER">Viewer — read only</option><option value="ADMIN">Admin — scoped fleet operations</option></>}</select></label><label className="mt-3 block text-sm text-slate-400">{existing?'New password (leave blank to keep current)':'Password'}<input name="password" type="password" required={!existing} minLength={10} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label>{existing&&!userAdmin&&<label className="mt-4 flex items-center gap-2 text-sm"><input name="isActive" type="checkbox" defaultChecked={existing.is_active}/> Account active</label>}</>}
    {role!=='SUPERADMIN'&&role!=='USERADMIN'&&<section className="mt-5"><h3 className="font-semibold">Company access</h3><p className="mb-3 text-xs text-slate-400">View grants access to the company’s records. Edit grants operational changes for that company. Edit includes view.</p><div className="overflow-x-auto rounded-lg border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3 text-left">Company</th><th className="p-3">View</th><th className="p-3">Edit</th></tr></thead><tbody>{companies.map(company=>{const item=access.find(value=>value.companyName===company.name)!;return <tr key={company.name} className="border-t border-slate-800"><td className="p-3">{company.name}</td><td className="text-center"><input aria-label={`View ${company.name}`} type="checkbox" checked={item.canView} onChange={event=>toggle(company.name,'canView',event.target.checked)}/></td><td className="text-center"><input aria-label={`Edit ${company.name}`} type="checkbox" disabled={role==='VIEWER'} checked={item.canEdit} onChange={event=>toggle(company.name,'canEdit',event.target.checked)}/></td></tr>})}</tbody></table></div>{companies.length===0&&<p className="rounded border border-slate-800 p-4 text-sm text-slate-400">No active company options are configured yet.</p>}</section>}
    {error&&<p className="mt-3 text-red-300">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-slate-700 px-4 py-2">Cancel</button><button disabled={busy} className="rounded-lg bg-blue-600 px-4 py-2 disabled:opacity-50">{busy?'Saving…':'Save User'}</button></div></form></div>
}
