'use client';
import { useEffect,useState } from 'react';
type Role='VIEWER'|'ADMIN'|'SUPERADMIN';
type User={id:string;username:string;display_name:string;role:Role;is_active:boolean;last_login_at:string|null;created_at:string};
export function UserManagementPage(){
  const [users,setUsers]=useState<User[]>([]),[show,setShow]=useState<User|null|true|false>(false),[notice,setNotice]=useState('');
  const load=()=>void fetch('/api/admin/users').then(async response=>{const body=await response.json();response.ok?setUsers(body.users):setNotice(body.error)});
  useEffect(load,[]);
  return <><header className="mb-8 flex items-start justify-between"><div><p className="text-sm font-semibold text-blue-400">Superadmin</p><h1 className="text-3xl font-bold">User Management</h1><p className="mt-2 text-slate-400">Viewers are read-only. Admins manage fleet operations. Superadmins also manage accounts.</p></div><button onClick={()=>setShow(true)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold">+ Add User</button></header>{notice&&<p className="mb-4 text-amber-300">{notice}</p>}<div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f]"><table className="w-full min-w-[850px] text-left"><thead className="text-sm text-slate-400"><tr><th className="p-4">User</th><th>Role</th><th>Status</th><th>Last Login</th><th>Created</th><th>Action</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-slate-800"><td className="p-4"><b>{user.display_name}</b><p className="text-sm text-slate-500">{user.username}</p></td><td><RoleBadge role={user.role}/></td><td className={user.is_active?'text-emerald-300':'text-red-300'}>{user.is_active?'Active':'Disabled'}</td><td>{user.last_login_at?new Date(user.last_login_at).toLocaleString():'Never'}</td><td>{new Date(user.created_at).toLocaleDateString()}</td><td><button onClick={()=>setShow(user)} className="rounded border border-slate-600 px-3 py-1 text-sm">Manage</button></td></tr>)}</tbody></table></div>{show&&<UserDialog existing={typeof show==='object'?show:null} onClose={()=>setShow(false)} onSaved={()=>{setShow(false);load()}}/>}</>;
}
function RoleBadge({role}:{role:Role}){const colors=role==='SUPERADMIN'?'border-purple-700 text-purple-300':role==='ADMIN'?'border-blue-700 text-blue-300':'border-slate-600 text-slate-300';return <span className={`rounded-full border px-2 py-1 text-xs font-semibold ${colors}`}>{role}</span>}
function UserDialog({existing,onClose,onSaved}:{existing:User|null;onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const payload={username:form.get('username'),displayName:form.get('displayName'),password:form.get('password'),role:form.get('role'),isActive:form.get('isActive')==='on'};const response=await fetch(existing?`/api/admin/users/${existing.id}`:'/api/admin/users',{method:existing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();setBusy(false);response.ok?onSaved():setError(body.error)};return <div className="fixed inset-0 z-30 grid place-items-center bg-black/75 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-xl border border-slate-700 bg-[#171b21] p-6"><h2 className="text-xl font-bold">{existing?'Manage User':'Add User'}</h2><label className="mt-4 block text-sm text-slate-400">Username<input name="username" required={!existing} disabled={Boolean(existing)} defaultValue={existing?.username||''} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2 disabled:opacity-60"/></label><label className="mt-3 block text-sm text-slate-400">Display name<input name="displayName" required defaultValue={existing?.display_name||''} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label><label className="mt-3 block text-sm text-slate-400">Role<select name="role" defaultValue={existing?.role||'VIEWER'} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"><option value="VIEWER">Viewer — read only</option><option value="ADMIN">Admin — fleet operations</option><option value="SUPERADMIN">Superadmin — users and operations</option></select></label><label className="mt-3 block text-sm text-slate-400">{existing?'New password (leave blank to keep current)':'Password'}<input name="password" type="password" required={!existing} minLength={10} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label>{existing&&<label className="mt-4 flex items-center gap-2 text-sm"><input name="isActive" type="checkbox" defaultChecked={existing.is_active}/> Account active</label>}{error&&<p className="mt-3 text-red-300">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-slate-700 px-4 py-2">Cancel</button><button disabled={busy} className="rounded-lg bg-blue-600 px-4 py-2">{busy?'Saving…':'Save User'}</button></div></form></div>}
