'use client';
import { useEffect,useState } from 'react';
import { canManage,useCurrentUser } from '@/lib/use-current-user';

export default function UnitDetails({params}:{params:Promise<{unitId:string}>}){
  const [id,setId]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[showReassign,setShowReassign]=useState(false); const user=useCurrentUser(); const mayManage=canManage(user);
  const load=(unitId=id)=>{if(!unitId)return;void fetch(`/api/units/${unitId}`).then(async response=>{const body=await response.json();response.ok?setData(body):setError(body.error)})};
  useEffect(()=>{void params.then(({unitId})=>{setId(unitId);load(unitId)})},[params]);
  if(error)return <main className="p-8 text-red-300">{error}</main>;
  if(!data)return <main className="p-8 text-slate-400">Loading unit…</main>;
  const unit=data.unit,current=unit.unit_registrations.find((item:any)=>item.is_active),canEditUnit=canManage(user)&&(user?.role==='SUPERADMIN'||user?.companyAccess?.some(access=>access.company_name===unit.company&&access.can_edit));
  const excuseWeek=async()=>{const reason=prompt('Why should the current PTI week be excused?');if(!reason)return;const response=await fetch(`/api/units/${id}/excuse`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})});const body=await response.json();if(response.ok)load();else setError(body.error)};
  return <main className="mx-auto max-w-7xl p-4 py-8 sm:p-8"><a href="/units" className="text-blue-400">← Assigned units</a><header className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-400">Unit history</p><h1 className="text-3xl font-bold">Unit {unit.unit_number}</h1><p className="mt-2 text-slate-400">{unit.company} · {unit.registration_status.replace('_',' ')}</p><p className="text-slate-400">{current?`${[current.driver_first_name,current.driver_last_name].filter(Boolean).join(' ')||`@${current.driver_username}`} · ${current.telegram_chat_title}`:'No active registration'}</p></div>{current&&canEditUnit&&<div className="flex gap-3"><button onClick={()=>void excuseWeek()} className="rounded-lg border border-slate-700 px-4 py-2 font-semibold">Excuse Current Week</button><button onClick={()=>setShowReassign(true)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold">Reassign Driver</button></div>}</header>
    {data.exclusions?.length>0&&<p className="mt-4 text-sm text-slate-400">Excused weeks: {data.exclusions.map((item:any)=>`${item.week_start}: ${item.reason}`).join(' · ')}</p>}
    {data.repeatIssues.map((issue:any)=><div key={issue.category} className="mt-5 rounded-xl border border-amber-800 bg-amber-950/30 p-4 text-amber-200">⚠ Repeat Issue — {issue.occurrences} {issue.category} defects in the last 8 weeks.</div>)}
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><Compliance title="Last 4 weeks" value={data.compliance4}/><Compliance title="Last 8 weeks" value={data.compliance8}/></div>
    <Table title="PTI History" heads={['PTI','Date','Driver at time','Review','Reviewer','Defects','Archive']} rows={data.ptis.map((pti:any)=>[pti.pti_reference,new Date(pti.created_at).toLocaleString(),pti.driver_name_snapshot||pti.driver_username_snapshot||'Unknown',pti.status,pti.reviewed_by||'—',pti.defect_count,pti.archive_url?<a key={pti.id} href={pti.archive_url} target="_blank" className="text-blue-400">Telegram ↗</a>:'—'])}/>
    <Table title="Defect History" heads={['Defect','PTI','Category','Description','Severity','Status','Created']} rows={data.defects.map((defect:any)=>[<a key={defect.id} href={`/defects/${defect.id}`} className="text-blue-400">{defect.defect_reference}</a>,`PTI-${String(defect.pti_number).padStart(6,'0')}`,defect.category,defect.description,defect.severity,defect.status,new Date(defect.created_at).toLocaleDateString()])}/>
    <Table title="Driver Assignment History" heads={['Driver','Telegram','Group','Start','End','Reason']} rows={data.assignments.map((assignment:any)=>[[assignment.driver_first_name,assignment.driver_last_name].filter(Boolean).join(' ')||assignment.driver_username||'Unknown',assignment.driver_username?`@${assignment.driver_username}`:'—',assignment.telegram_group_title,assignment.started_at?new Date(assignment.started_at).toLocaleString():'Unknown',assignment.ended_at?new Date(assignment.ended_at).toLocaleString():'Current',assignment.reason||'—'])}/>
    {showReassign&&<Reassign id={id} onClose={()=>setShowReassign(false)} onSaved={()=>{setShowReassign(false);load()}}/>}
  </main>;
}
function Compliance({title,value}:{title:string;value:any}){return <section className="rounded-xl border border-slate-800 bg-[#15191f] p-5"><p className="text-sm text-slate-400">{title}</p><p className="text-4xl font-black text-blue-400">{value.score===null?'—':`${value.score}%`}</p><p className="mt-2 text-sm text-slate-400">Expected {value.expected} · Submitted {value.submitted} · Missing {value.missing} · Excused {value.excused} · Resends {value.resends}</p></section>}
function Table({title,heads,rows}:{title:string;heads:string[];rows:React.ReactNode[][]}){return <section className="mt-8"><h2 className="mb-3 text-xl font-bold">{title}</h2><div className="overflow-x-auto rounded-xl border border-slate-800 bg-[#15191f]"><table className="w-full min-w-[800px] text-left text-sm"><thead className="text-slate-400"><tr>{heads.map(head=><th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t border-slate-800">{row.map((cell,cellIndex)=><td className="max-w-xs p-3" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-slate-500">No history available.</p>}</div></section>}
function Reassign({id,onClose,onSaved}:{id:string;onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const response=await fetch(`/api/units/${id}/reassign`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:form.get('username')||null,telegramUserId:form.get('telegramUserId')||null,firstName:form.get('firstName')||null,lastName:form.get('lastName')||null,reason:form.get('reason')||null})});const body=await response.json();setBusy(false);response.ok?onSaved():setError(body.error)};return <div className="fixed inset-0 z-30 grid place-items-center bg-black/75 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-xl border border-slate-700 bg-[#171b21] p-6"><h2 className="text-xl font-bold">Reassign Driver</h2><p className="mt-2 text-sm text-slate-400">The current assignment will be closed; existing PTIs keep their historical driver.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="firstName" label="First name"/><Field name="lastName" label="Last name"/><Field name="username" label="Telegram username" placeholder="driver_username"/><Field name="telegramUserId" label="Telegram numeric ID (optional)"/></div><label className="mt-3 block text-sm text-slate-400">Reason<input name="reason" placeholder="Driver changed, truck swap…" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label>{error&&<p className="mt-3 text-red-300">{error}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-slate-700 px-4 py-2">Cancel</button><button disabled={busy} className="rounded-lg bg-blue-600 px-4 py-2">{busy?'Saving…':'Reassign'}</button></div></form></div>}
function Field({name,label,placeholder}:{name:string;label:string;placeholder?:string}){return <label className="text-sm text-slate-400">{label}<input name={name} placeholder={placeholder} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2"/></label>}
